### ISSUE TITLE
how to fix position & request update to change only active date color and today color for calender

### ISSUE THREAD

**Issue by liem84** [thedatepicker/thedatepicker#6]
hi. this script is so wonderfull. but can anyone help how to fix position of the script? and also how to change only today color and saturday, sunday color only?

<img width="332" alt="111" src="https://user-images.githubusercontent.com/71325400/160526472-75c06eb6-e242-41b8-ab46-2d9a97755501.png">

<img width="331" alt="222" src="https://user-images.githubusercontent.com/71325400/160526474-a0d13a77-75e1-46ec-81dc-9cc48a1a44cb.png">

**Comment by VladaHejda** [comment]
I assume that by position you mean that the second DP is aligned to the left but not under the input.
It is likely because both inputs are inline like `<div><input id=dp1><input id=dp2></div>`
I can think of two possible solutions:
- wrap each input in a block element
- or modify your local css somehow to fix positions, focus on an element with the class `the-datepicker__container`

______________

Today color can be defined by `the-datepicker__day--today` class, for the weekend you can add class by `addCellClassesResolver`:
```
datepicker.options.addCellClassesResolver((day) => {
	if (
		day.dayOfWeek === TheDatepicker.DayOfWeek.Saturday
		|| day.dayOfWeek === TheDatepicker.DayOfWeek.Sunday
	) {
		return ['weekend'];
	}
});
datepicker.render();
```

then you just define styles:

`.weekend span, .the-datepicker__day--today span { background-color: yellow; }`

All types of dates has it's predefined classes, just examine them in the HTML.
